server:
  port: 8081

spring:
  application:
    name: user-service
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
