server:
  port: 8082

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb+srv://sokkhannpol02:qxICaW3LR17xHWlz@cluster1.osiqajg.mongodb.net/ecomerce-microservice?retryWrites=true&w=majority&appName=Cluster1

# register service into eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: # sensitive case must have this
    hostname: localhost
    prefer-ip-address: true
