server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sokkhann/E-Commerce-Microservice.git
          search-paths: file-configuration  # Subdirectory where config files are stored
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true