server:
  port: 8888

spring:
  application:
    name: configuration server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sokkhann/E-Commerce-Microservice/config-server  # Or remote Git URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true